FROM quay.io/keycloak/keycloak:26.1.0 as builder

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

# Configure a database vendor
ENV KC_DB=postgres

WORKDIR /opt/keycloak
# For optimizing the build for production
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:26.1.0
COPY --from=builder /opt/keycloak/ /opt/keycloak/

# Change these values for production
ENV KC_HOSTNAME=keycloak-pfe.onetech-group.corp
ENV KC_HOSTNAME_STRICT=true
ENV KC_HOSTNAME_STRICT_HTTPS=true
ENV KC_HTTP_ENABLED=false
ENV KC_PROXY=edge

# Database configuration
ENV KC_DB=postgres
ENV KC_DB_URL=jdbc:postgresql://10.112.61.91:5432/keycloak
ENV KC_DB_USERNAME=keycloak
ENV KC_DB_PASSWORD=keycloak

# Cache configuration using infinispan
ENV KC_CACHE=ispn
ENV KC_CACHE_STACK=kubernetes

# Logging configuration
ENV KC_LOG_LEVEL=INFO
ENV KC_LOG_CONSOLE_OUTPUT=json

# Set memory options
#ENV JAVA_OPTS="-Xms512m -Xmx2048m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m"
#ENV JAVA_OPTS_APPEND="-Djava.net.preferIPv4Stack=true -Djgroups.bind_addr=\$(hostname -i)"

# Add custom theme if needed
# COPY themes/custom /opt/keycloak/themes/custom

# Add custom providers if needed
# COPY providers/* /opt/keycloak/providers/

EXPOSE 8443

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start"]
